### PR TITLE
Fix urgency

### PR DESCRIPTION
**Pull request by dhjw**
It appears the urgency hint implementation was incomplete.

### CODE REVIEW

**Comment by igo95862** [comment]
Hello @dhjw 

Thank you for noticing this. However, the standard documentation says that the urgency D-Bus type should be byte `y` not integer.

https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#hints

**Comment by dhjw** [comment]
It's working as int, and [others](https://pychao.com/2021/03/01/sending-desktop-notification-in-linux-with-python-with-d-bus-directly/) seem to just use int, but it would be nice to follow the spec. My attempts to convert to bytes seem to cause a problem elsewhere. I will see if I can figure it out or perhaps you can.

**Comment by igo95862** [comment]
What kind of issue are you experiencing? It is still an integer just an 8-bit one. Simply changing the D-Bus type to `y` should work?

**Comment by dhjw** [comment]
yes, you're right

**Comment by dhjw** [comment]
I missed your advice and was trying 'a' and thought a conversion function would be necessary. 😅 Should be good now. No more errors and notifications are coming up with the right level. Thanks

**Comment by igo95862** [comment]
There is a D-Bus to Python types table in the python-sdbus documentation: https://python-sdbus.readthedocs.io/en/latest/general.html#d-bus-types-conversion

**Pull request merged**
